version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tax_db
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-wellness_orders}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tax_redis
    ports:
      - "6379:6379"
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - redis_data:/data

  nominatim:
    image: mediagis/nominatim:4.4
    container_name: tax_nominatim
    environment:
      PBF_PATH: /nominatim/data/new-york-latest.osm.pbf
      REPLICATION_URL: ""
      NOMINATIM_PASSWORD: nominatim
    volumes:
      - ./nominatim-data:/nominatim/data
      - nominatim_data:/var/lib/postgresql/14/main
    networks:
      - backend_network
    shm_size: 1g
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: tax_backend
    env_file: .env
    depends_on:
      - db
      - redis
      - nominatim
    networks:
      - backend_network
      - proxy_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: tax_frontend
    env_file: .env
    depends_on:
      - backend
    networks:
      - proxy_network
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: tax_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy_network
    depends_on:
      - frontend
      - backend

networks:
  backend_network:
  proxy_network:


volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
  nominatim_data:
